<?php

$sql = "CREATE TABLE animeList (
	id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year VARCHAR(100) NOT NULL,
    info VARCHAR(100),
    addedAt VARCHAR(100) NOT NULL DEFAULT CURRENT_TIME,
    PRIMARY KEY (id)
);";